# Generated by Django 5.1.6 on 2025-02-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_patientinfo_dietrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Accounts.patientinfo'),
            preserve_default=False,
        ),
    ]
