# Generated by Django 5.1.6 on 2025-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_patient_patient_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrecommendation',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietrecommendation',
            name='cuisine_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='recommended_meals',
            field=models.TextField(help_text='List recommended meals'),
        ),
    ]
