# Generated by Django 5.1.6 on 2025-02-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_appointment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='yoga_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SweatSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CalorieRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('intake', models.PositiveIntegerField(help_text='Calories consumed')),
                ('burnt', models.PositiveIntegerField(help_text='Calories burnt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories', to='Accounts.patient')),
            ],
        ),
    ]
