# Generated by Django 5.1.6 on 2025-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_soulstretch_sweatspot_calorierecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulstretch',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='yoga_videos/'),
        ),
        migrations.AddField(
            model_name='sweatspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
        migrations.AddField(
            model_name='sweatspot',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/'),
        ),
    ]
