# Generated by Django 5.1.6 on 2025-02-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_customuser_managers_patientinfo_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='user',
        ),
    ]
