# Generated by Django 5.1.6 on 2025-02-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_patientinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='user',
        ),
    ]
