# Generated by Django 5.1.6 on 2025-02-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_patientinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='calorierecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_info',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='SoulStretch',
        ),
        migrations.DeleteModel(
            name='SweatSpot',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='CalorieRecord',
        ),
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientInfo',
        ),
    ]
