# Generated by Django 5.1.6 on 2025-03-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulstretch',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soulstrech', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweatspot',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sweatspot', to='patient.patient'),
            preserve_default=False,
        ),
    ]
